name: Daily Counter Update

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pillow
        
    - name: Generate images
      env:
        PYTHONIOENCODING: "UTF-8"
      run: python generate_images.py

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add assets/*.png
        git commit -m "Auto-update counter images" || exit 0
        git push